/**
 * Seed real importado de Tecnopano-2.0 (github.com/Furia300/Tecnopano-2.0/server/seed.ts).
 * 164 produtos reais — fonte oficial. NÃO editar manualmente; re-puxar do upstream.
 */
export interface ProdutoSeed {
  codigo: string | null;
  nome: string | null;
  descricao: string | null;
  cor: string | null;
  medida: string | null;
  acabamento: string | null;
  unidadeMedida: string | null;
  precoCusto: number | null;
  precoVenda: number | null;
  foto: string | null;
  notaFiscal: string | null;
  ativo: boolean;
}

export const produtosSeed: ProdutoSeed[] = [
    {
    codigo: "37",
    nome: "Tecnopano Fur 2.2",
    descricao: "Tecnopano Fur 2.2",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "20x20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "20x20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "39",
    nome: "Tecnopano Gr 3.3 Zig-Zag",
    descricao: "Tecnopano Gr 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "42",
    nome: "Tecnopano Gr Por Kilo",
    descricao: "Tecnopano Gr Por Kilo",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "50x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "45",
    nome: "Tecnopano Kit Oficina Limpa",
    descricao: "Tecnopano Kit Oficina Limpa",
    acabamento: "Limpa",
    cor: "Branco",
    medida: "37x37 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "37x37 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "47",
    nome: "Tecnopano Lençol Branco Maca",
    descricao: "Tecnopano Lençol Branco Maca",
    acabamento: "Maca",
    cor: "Branco",
    medida: "1.10x2.20 M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "1.10x2.20 M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "54",
    nome: "Tecnopano Malha Esp 2.2",
    descricao: "Tecnopano Malha Esp 2.2",
    acabamento: "Especial",
    cor: "Branco",
    medida: "20x20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "20x20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "60",
    nome: "Tecnopano Saco Alvejado Para Limpeza",
    descricao: "Tecnopano Saco Alvejado Para Limpeza",
    acabamento: "Alvejado",
    cor: "Branco",
    medida: "50x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "58",
    nome: "Tecnopano Pano Microfibra",
    descricao: "Tecnopano Pano Microfibra",
    acabamento: "Microfibra",
    cor: "Variado",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "48",
    nome: "Tecnopano Lençol Branco Queen",
    descricao: "Tecnopano Lençol Branco Queen",
    acabamento: "Queen",
    cor: "Branco",
    medida: "2.80x2.00 M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "2.80x2.00 M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "55",
    nome: "Tecnopano Malha Especial 4.4",
    descricao: "Tecnopano Malha Especial 4.4",
    acabamento: "Especial",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "9",
    nome: "Tecnopano Barreiras De Contenção",
    descricao: "Tecnopano Barreiras De Contenção",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "80 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "80 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "3",
    nome: "Tecnopano Panos Para Limpeza Industrial Tipo A9",
    descricao: "Tecnopano Panos Para Limpeza Industrial Tipo A9",
    acabamento: "Overlock",
    cor: "Vermelho",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "3",
    nome: "Tecnopano Panos Para Limpeza Industrial Tipo A9",
    descricao: "Tecnopano Panos Para Limpeza Industrial Tipo A9",
    acabamento: "Overlock",
    cor: "Azul",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "3",
    nome: "Tecnopano Panos Para Limpeza Industrial Tipo A9",
    descricao: "Tecnopano Panos Para Limpeza Industrial Tipo A9",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "3",
    nome: "Tecnopano Panos Para Limpeza Industrial Tipo A9",
    descricao: "Tecnopano Panos Para Limpeza Industrial Tipo A9",
    acabamento: "Overlock",
    cor: "Verde",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "15",
    nome: "Tecnopano Br Algodão 3.35 Corte Reto",
    descricao: "Tecnopano Br Algodão 3.35 Corte Reto",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "30x35 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x35 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "11",
    nome: "Tecnopano Br Algodão 2.2 Zig-Zag",
    descricao: "Tecnopano Br Algodão 2.2 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "20x20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "20x20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "13",
    nome: "Tecnopano Br Algodão 3.2 Zig-Zag",
    descricao: "Tecnopano Br Algodão 3.2 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "30x20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "14",
    nome: "Tecnopano Br Algodão 3.3 Zig-Zag",
    descricao: "Tecnopano Br Algodão 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "25",
    nome: "Tecnopano Gr Diversas Cores 3.3 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Cinza",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "16",
    nome: "Tecnopano Br Algodão 4.4 Zig-Zag",
    descricao: "Tecnopano Br Algodão 4.4 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "40x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "21",
    nome: "Tecnopano Br Algodão 5.5 Por Kilo",
    descricao: "Tecnopano Br Algodão 5.5 Por Kilo",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "50x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "19",
    nome: "Tecnopano Br Algodão 80X100 Cort",
    descricao: "Tecnopano Br Algodão 80X100 Cort",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "80x100 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "80x100 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "24",
    nome: "Tecnopano Br Algodão 4.5 Zig-Zag",
    descricao: "Tecnopano Br Algodão 4.5 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "40x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "22",
    nome: "Tecnopano Br Algodão 2.2 Overlok",
    descricao: "Tecnopano Br Algodão 2.2 Overlok",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "20x20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "20x20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "25",
    nome: "Tecnopano Gr Diversas Cores 3.3 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Azul",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "18",
    nome: "Tecnopano Br Algodão Frz Por Kilo 4.6",
    descricao: "Tecnopano Br Algodão Frz Por Kilo 4.6",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "25",
    nome: "Tecnopano Gr Diversas Cores 3.3 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Verde",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "18",
    nome: "Tecnopano Br Algodão 4.7 Por Kilo",
    descricao: "Tecnopano Br Algodão 4.7 Por Kilo",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "26",
    nome: "Tecnopano Gr Diversas Cores 4.4 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 4.4 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Cinza",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "25",
    nome: "Tecnopano Gr Diversas Cores 3.3 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "26",
    nome: "Tecnopano Gr Diversas Cores 4.4 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 4.4 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "30",
    nome: "Retalho Textil Para Beneficiamento",
    descricao: "Retalho Textil Para Beneficiamento",
    acabamento: "Novo",
    cor: "Branco",
    medida: "Infinita",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "Infinita",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "27",
    nome: "Tecnopano Gr Diversas Cores 8.8 Overlok",
    descricao: "Tecnopano Gr Diversas Cores 8.8 Overlok",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "80x80 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "80x80 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "27",
    nome: "Tecnopano Gr Diversas Cores 8.8 Overlok",
    descricao: "Tecnopano Gr Diversas Cores 8.8 Overlok",
    acabamento: "Overlock",
    cor: "Cinza",
    medida: "80x80 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "80x80 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "26",
    nome: "Tecnopano Gr Diversas Cores 4.4 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 4.4 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Verde",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "27",
    nome: "Tecnopano Gr Diversas Cores 8.8 Overlok",
    descricao: "Tecnopano Gr Diversas Cores 8.8 Overlok",
    acabamento: "Overlock",
    cor: "Verde",
    medida: "80x80 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "80x80 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "27",
    nome: "Tecnopano Gr Diversas Cores 8.8 Overlok",
    descricao: "Tecnopano Gr Diversas Cores 8.8 Overlok",
    acabamento: "Overlock",
    cor: "Azul",
    medida: "80x80 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "80x80 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "26",
    nome: "Tecnopano Gr Diversas Cores 4.4 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 4.4 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Azul",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "39",
    nome: "Tecnopano Gr 3.3 Zig-Zag",
    descricao: "Tecnopano Gr 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Azul",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "35",
    nome: "Tecnopano Faixa Ind Branca Por Kilo",
    descricao: "Tecnopano Faixa Ind Branca Por Kilo",
    acabamento: "Retalho",
    cor: "Branco",
    medida: "25x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "25x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "34",
    nome: "Tecnopano Estopas Por Kilo",
    descricao: "Tecnopano Estopas Por Kilo",
    acabamento: "Estopinha",
    cor: "Estopa Crua",
    medida: "Variável",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "Variável",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "39",
    nome: "Tecnopano Gr 3.3 Zig-Zag",
    descricao: "Tecnopano Gr 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Cinza",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "39",
    nome: "Tecnopano Gr 3.3 Zig-Zag",
    descricao: "Tecnopano Gr 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "39",
    nome: "Tecnopano Gr 3.3 Zig-Zag",
    descricao: "Tecnopano Gr 3.3 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Verde",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "42",
    nome: "Tecnopano Gr Por Kilo",
    descricao: "Tecnopano Gr Por Kilo",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "50x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "56",
    nome: "Tecnopano Manta Absorção 4.5",
    descricao: "Tecnopano Manta Absorção 4.5",
    acabamento: "Plástico",
    cor: "Branco",
    medida: "40x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "57",
    nome: "Tecnopano  Trapo colorido por kilo",
    descricao: "Tecnopano  Trapo colorido por kilo",
    acabamento: "Colorido",
    cor: "Variado",
    medida: "15x15 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "15x15 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "61",
    nome: "Tecnopano Pano Tecnolim",
    descricao: "Tecnopano Pano Tecnolim",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "62",
    nome: "Tecnopano Tl 3.3",
    descricao: "Tecnopano Tl 3.3",
    acabamento: "Corte-Reto",
    cor: "Preto",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "62",
    nome: "Tecnopano Tl 3.3",
    descricao: "Tecnopano Tl 3.3",
    acabamento: "Corte-Reto",
    cor: "Azul",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "62",
    nome: "Tecnopano Tl 3.3",
    descricao: "Tecnopano Tl 3.3",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "64",
    nome: "Tecnopano Tnt Liso 3.3",
    descricao: "Tecnopano Tnt Liso 3.3",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "79",
    nome: "Tecnopano Pp A9",
    descricao: "Tecnopano Pp A9",
    acabamento: "Overlock",
    cor: "Verde",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "90",
    nome: "Tecnopano Malha Algodão",
    descricao: "Tecnopano Malha Algodão",
    acabamento: "Algodão",
    cor: "Branco",
    medida: "20x20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "20x20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "79",
    nome: "Tecnopano Pp A9",
    descricao: "Tecnopano Pp A9",
    acabamento: "Overlock",
    cor: "Azul",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "85",
    nome: "Tecnopano Gr Branco 4.4 Overlok",
    descricao: "Tecnopano Gr Branco 4.4 Overlok",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "79",
    nome: "Tecnopano Pp A9",
    descricao: "Tecnopano Pp A9",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "85",
    nome: "Tecnopano Gr 3.5 Overlok",
    descricao: "Tecnopano Gr 3.5 Overlok",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "35x35 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "35x35 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "79",
    nome: "Tecnopano Pp A9",
    descricao: "Tecnopano Pp A9",
    acabamento: "Overlock",
    cor: "Vermelho",
    medida: "33x33 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "33x33 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "84",
    nome: "Tecnopano Br Algodão 4.6 Frz Corte Reto",
    descricao: "Tecnopano Br Algodão 4.6 Frz Corte Reto",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "95",
    nome: "H-Pano Limpeza 40X40 Cm Costurado Pac 100",
    descricao: "H-Pano Limpeza 40X40 Cm Costurado Pac 100",
    acabamento: "Algodão",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "93",
    nome: "Tecnopano Malha Algodão Por Kilo",
    descricao: "Tecnopano Malha Algodão Por Kilo",
    acabamento: "Algodão",
    cor: "Branco",
    medida: "12x12 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "12x12 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "117",
    nome: "Tecnopano A9 Por Kilo",
    descricao: "Tecnopano A9 Por Kilo",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "111",
    nome: "Tecnopano Tecnowipers t 30X30 Pct Com 50 Und",
    descricao: "Tecnopano Tecnowipers t 30X30 Pct Com 50 Und",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "107",
    nome: "Tecnopano A2 4.7",
    descricao: "Tecnopano A2 4.7",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "40x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "102",
    nome: "Tecnopano Atm",
    descricao: "Tecnopano Atm",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "100",
    nome: "Tecnopano Fur 4.8",
    descricao: "Tecnopano Fur 4.8",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x80 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x80 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "99",
    nome: "Tecnopano Pano Algodao 4.3 Overlok",
    descricao: "Tecnopano Pano Algodao 4.3 Overlok",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "99",
    nome: "Tecnopano Pano Reciclado 30X40 Overlok",
    descricao: "Tecnopano Pano Reciclado 30X40 Overlok",
    acabamento: "Reciclado",
    cor: "Branco",
    medida: "30x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "120",
    nome: "Tecnopano Gr Diversas Cores 5.7 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 5.7 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Cinza",
    medida: "50x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "120",
    nome: "Tecnopano Gr Diversas Cores 5.7 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 5.7 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Azul",
    medida: "50x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "137",
    nome: "Tecnopano Br Algodão Listrado 4.4",
    descricao: "Tecnopano Br Algodão Listrado 4.4",
    acabamento: "Zig-Zag",
    cor: "Listrado",
    medida: "37x37 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "37x37 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "131",
    nome: "Tecnopano Fronha Por Kilo",
    descricao: "Tecnopano Fronha Por Kilo",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "40x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "130",
    nome: "Tecnopano Gru Diversas Cores 3.4",
    descricao: "Tecnopano Gru Diversas Cores 3.4",
    acabamento: "Zig-Zag",
    cor: "Variado",
    medida: "30x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "120",
    nome: "Tecnopano Gr Diversas Cores 5.7 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 5.7 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "50x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "123",
    nome: "Tecnopano Faixa Ind Colorida Por Kilo",
    descricao: "Tecnopano Faixa Ind Colorida Por Kilo",
    acabamento: "Retalho",
    cor: "Colorida",
    medida: "25x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "25x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "120",
    nome: "Tecnopano Gr Diversas Cores 5.7 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 5.7 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Verde",
    medida: "50x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "147",
    nome: "Tecnopano Pega Pó 40X40 Sem Impregnação",
    descricao: "Tecnopano Pega Pó 40X40 Sem Impregnação",
    acabamento: "Sem Impregnação",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "133",
    nome: "Tecnopano Retalho Material Sintetico Por Kilo",
    descricao: "Tecnopano Retalho Material Sintetico Por Kilo",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "Variável",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "Variável",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "147",
    nome: "Tecnopano Pega Pó 4.4 Sem Impregnação",
    descricao: "Tecnopano Pega Pó 4.4 Sem Impregnação",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "158",
    nome: "Tecnopano Br Algodão 4.4 Com Overlok",
    descricao: "Tecnopano Br Algodão 4.4 Com Overlok",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "155",
    nome: "Tecnopano Tecnowipers  Medida 10X10",
    descricao: "Tecnopano Tecnowipers  Medida 10X10",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "10x10 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "10x10 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "154",
    nome: "Tecnopano Br Algodão 3.2 Com Overlok",
    descricao: "Tecnopano Br Algodão 3.2 Com Overlok",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "30x20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "148",
    nome: "Tecnopano Enxoval Por Kilo",
    descricao: "Tecnopano Enxoval Por Kilo",
    acabamento: "Dropdown",
    cor: "Branco",
    medida: "Todos",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "Todos",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "162",
    nome: "Tecnopano Gr 4.4 Kilo",
    descricao: "Tecnopano Gr 4.4 Kilo",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "50x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "50x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "163",
    nome: "Tecnopano Br Algodão 3.4 Kilo",
    descricao: "Tecnopano Br Algodão 3.4 Kilo",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "30x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "160",
    nome: "Tecnopano Fur 4.4",
    descricao: "Tecnopano Fur 4.4",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "160",
    nome: "Tecnopano Pano Fur 4.4",
    descricao: "Tecnopano Pano Fur 4.4",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "161",
    nome: "Tecnopano Br Algodão 3.4 Zig-Zag",
    descricao: "Tecnopano Br Algodão 3.4 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Branco",
    medida: "30x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "169",
    nome: "Tecnopano Tecnowipers  Com 100 Kilo",
    descricao: "Tecnopano Tecnowipers  Com 100 Kilo",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "168",
    nome: "Tecnopano Gru 4.7 Por Kilo",
    descricao: "Tecnopano Gru 4.7 Por Kilo",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "40x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "87",
    nome: "Tecnopano Uniformes",
    descricao: "Tecnopano Uniformes",
    acabamento: "Uniforme Kilo",
    cor: "Variado",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "87",
    nome: "Tecnopano Uniformes",
    descricao: "Tecnopano Uniformes",
    acabamento: "Uniforme Kilo",
    cor: "Variado",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "87",
    nome: "Tecnopano Uniformes",
    descricao: "Tecnopano Uniformes",
    acabamento: "Uniforme Kilo",
    cor: "Variado",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "87",
    nome: "Tecnopano Uniforme",
    descricao: "Tecnopano Uniforme",
    acabamento: "Uniformes Kilo",
    cor: "Variado",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "184",
    nome: "Tecnopano Avental Verde",
    descricao: "Tecnopano Avental Verde",
    acabamento: "Corte-Reto",
    cor: "Verde",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "184",
    nome: "Tecnopano Avental Verde",
    descricao: "Tecnopano Avental Verde",
    acabamento: "Corte-Reto",
    cor: "Verde",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "184",
    nome: "Tecnopano Avental Verde",
    descricao: "Tecnopano Avental Verde",
    acabamento: "Corte-Reto",
    cor: "Verde",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "184",
    nome: "Tecnopano Avental Verde",
    descricao: "Tecnopano Avental Verde",
    acabamento: "Corte-Reto",
    cor: "Verde",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "178",
    nome: "Gs Branco Overlocado  Sabesp",
    descricao: "Gs Branco Overlocado  Sabesp",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "105",
    nome: "Tecnopano Vestimenta Frz Unidade",
    descricao: "Tecnopano Vestimenta Frz Unidade",
    acabamento: "Corte-Reto",
    cor: "Florzinha",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "105",
    nome: "Tecnopano Vestimenta Frz Unidade",
    descricao: "Tecnopano Vestimenta Frz Unidade",
    acabamento: "Corte-Reto",
    cor: "Florzinha",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "105",
    nome: "Tecnopano Vestimenta Frz Unidade",
    descricao: "Tecnopano Vestimenta Frz Unidade",
    acabamento: "Corte-Reto",
    cor: "Florzinha",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "105",
    nome: "Tecnopano Vestimenta Frz Unidade 4.7",
    descricao: "Tecnopano Vestimenta Frz Unidade 4.7",
    acabamento: "Corte-Reto",
    cor: "Florzinha",
    medida: "4.7",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "4.7",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "2",
    nome: "Tecnopano Vestimenta De Proteção Individual",
    descricao: "Tecnopano Vestimenta De Proteção Individual",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "2",
    nome: "Tecnopano Vestimenta De Proteção Individual",
    descricao: "Tecnopano Vestimenta De Proteção Individual",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "56",
    nome: "Tecnopano Manta Absorção 4.5",
    descricao: "Tecnopano Manta Absorção 4.5",
    acabamento: "Plástico",
    cor: "Branco",
    medida: "40x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "2",
    nome: "Tecnopano Vestimenta De Proteção Individual",
    descricao: "Tecnopano Vestimenta De Proteção Individual",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "2",
    nome: "Tecnopano Vestimenta De Proteção Individual",
    descricao: "Tecnopano Vestimenta De Proteção Individual",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "73",
    nome: "Tecnopano Vestimenta De Proteção Individual Diversas Cores",
    descricao: "Tecnopano Vestimenta De Proteção Individual Diversas Cores",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "73",
    nome: "Tecnopano Vestimenta De Proteção Individual Diversas Cores",
    descricao: "Tecnopano Vestimenta De Proteção Individual Diversas Cores",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "9",
    nome: "Tecnopano Barreiras De Contenção",
    descricao: "Tecnopano Barreiras De Contenção",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "80 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "80 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "73",
    nome: "Tecnopano Vestimenta De Proteção Individual Diversas Cores",
    descricao: "Tecnopano Vestimenta De Proteção Individual Diversas Cores",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "73",
    nome: "Tecnopano Vestimenta De Proteção Individual Diversas Cores",
    descricao: "Tecnopano Vestimenta De Proteção Individual Diversas Cores",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "103",
    nome: "Tecnopano Par Luvas",
    descricao: "Tecnopano Par Luvas",
    acabamento: "Reciclada",
    cor: "Cinza",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "103",
    nome: "Tecnopano Par Luvas",
    descricao: "Tecnopano Par Luvas",
    acabamento: "Reciclada",
    cor: "Cinza",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "103",
    nome: "Tecnopano Par Luvas",
    descricao: "Tecnopano Par Luvas",
    acabamento: "Reciclada",
    cor: "Cinza",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "103",
    nome: "Tecnopano Par Luvas",
    descricao: "Tecnopano Par Luvas",
    acabamento: "Reciclada",
    cor: "Cinza",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "76",
    nome: "Tecnopano Capote Traçado",
    descricao: "Tecnopano Capote Traçado",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "2.00x1.00 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "2.00x1.00 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "109",
    nome: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    descricao: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    acabamento: "Corte-Reto",
    cor: "Bege",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "105",
    nome: "Tecnopano Vestimenta Frz Unidade",
    descricao: "Tecnopano Vestimenta Frz Unidade",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "105",
    nome: "Tecnopano Vestimenta Frz Unidade",
    descricao: "Tecnopano Vestimenta Frz Unidade",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "105",
    nome: "Tecnopano Vestimenta Frz Unidade",
    descricao: "Tecnopano Vestimenta Frz Unidade",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "105",
    nome: "Tecnopano Vestimenta Frz Unidade",
    descricao: "Tecnopano Vestimenta Frz Unidade",
    acabamento: "Corte-Reto",
    cor: "Variado",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "109",
    nome: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    descricao: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    acabamento: "Corte-Reto",
    cor: "Verde",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "109",
    nome: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    descricao: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    acabamento: "Corte-Reto",
    cor: "Verde",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "109",
    nome: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    descricao: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    acabamento: "Corte-Reto",
    cor: "Verde",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "109",
    nome: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    descricao: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    acabamento: "Corte-Reto",
    cor: "Bege",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "109",
    nome: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    descricao: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    acabamento: "Corte-Reto",
    cor: "Verde",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Par De Luvas De Raspa",
    descricao: "Tecnopano Par De Luvas De Raspa",
    acabamento: "Reciclada",
    cor: "Branco",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "109",
    nome: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    descricao: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    acabamento: "Corte-Reto",
    cor: "Bege",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "109",
    nome: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    descricao: "Tecnopano Conjunto Hidrorepelente Para Reforma",
    acabamento: "Corte-Reto",
    cor: "Bege",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Par De Luvas De Raspa",
    descricao: "Tecnopano Par De Luvas De Raspa",
    acabamento: "Reciclada",
    cor: "Branco",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Par De Luvas De Raspa",
    descricao: "Tecnopano Par De Luvas De Raspa",
    acabamento: "Reciclada",
    cor: "Preto",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Par De Luvas De Raspa",
    descricao: "Tecnopano Par De Luvas De Raspa",
    acabamento: "Reciclada",
    cor: "Branco",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Par De Luvas De Raspa",
    descricao: "Tecnopano Par De Luvas De Raspa",
    acabamento: "Reciclada",
    cor: "Preto",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Par De Luvas De Raspa",
    descricao: "Tecnopano Par De Luvas De Raspa",
    acabamento: "Reciclada",
    cor: "Preto",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Luvas De Malha E Raspa",
    descricao: "Tecnopano Luvas De Malha E Raspa",
    acabamento: "Reciclada",
    cor: "Preto",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Luvas De Malha E Raspa",
    descricao: "Tecnopano Luvas De Malha E Raspa",
    acabamento: "Reciclada",
    cor: "Preto",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Par De Luvas De Raspa",
    descricao: "Tecnopano Par De Luvas De Raspa",
    acabamento: "Reciclada",
    cor: "Preto",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Par De Luvas De Raspa",
    descricao: "Tecnopano Par De Luvas De Raspa",
    acabamento: "Reciclada",
    cor: "Branco",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Luvas De Malha E Raspa",
    descricao: "Tecnopano Luvas De Malha E Raspa",
    acabamento: "Reciclada",
    cor: "Branco",
    medida: "P",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Luvas De Malha E Raspa",
    descricao: "Tecnopano Luvas De Malha E Raspa",
    acabamento: "Reciclada",
    cor: "Branco",
    medida: "M",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "M",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Luvas De Malha E Raspa",
    descricao: "Tecnopano Luvas De Malha E Raspa",
    acabamento: "Reciclada",
    cor: "Branco",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Luvas De Malha E Raspa",
    descricao: "Tecnopano Luvas De Malha E Raspa",
    acabamento: "Reciclada",
    cor: "Branco",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Luvas De Malha E Raspa",
    descricao: "Tecnopano Luvas De Malha E Raspa",
    acabamento: "Reciclada",
    cor: "Preto",
    medida: "G",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "G",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "157",
    nome: "Tecnopano Manta Fina Reciclad",
    descricao: "Tecnopano Manta Fina Reciclad",
    acabamento: "Reciclada",
    cor: "Variado",
    medida: "1.10x2.20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "1.10x2.20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "165",
    nome: "Tecnopano Gaiola P",
    descricao: "Tecnopano Gaiola P",
    acabamento: "Ferro",
    cor: "Dourada",
    medida: "1.80x0.50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "1.80x0.50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "164",
    nome: "Tecnopano Gaiola G",
    descricao: "Tecnopano Gaiola G",
    acabamento: "Ferro",
    cor: "Cinza",
    medida: "1.00x1.70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "1.00x1.70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "156",
    nome: "Tecnopano Manta Reciclada",
    descricao: "Tecnopano Manta Reciclada",
    acabamento: "Reciclada",
    cor: "Variado",
    medida: "1.10x2.20 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "1.10x2.20 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "150",
    nome: "Tecnopano Capa de Fardo",
    descricao: "Tecnopano Capa de Fardo",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "113",
    nome: "Tecnopano Edredon Kilo",
    descricao: "Tecnopano Edredon Kilo",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "1.20x2.40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "1.20x2.40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "110",
    nome: "Tecnopano Luvas De Malha E Raspa",
    descricao: "Tecnopano Luvas De Malha E Raspa",
    acabamento: "Reciclada",
    cor: "Preto",
    medida: "GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "207",
    nome: "Toalha por Kilo",
    descricao: "Toalha por Kilo",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "200",
    nome: "Capa Fardo Corte Reto 4.5",
    descricao: "Capa Fardo Corte Reto 4.5",
    acabamento: "Corte-Reto",
    cor: "Branco",
    medida: "40x50 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x50 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "26",
    nome: "Tecnopano Gr Diversas Cores 3.5 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 3.5 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Diversas Cores",
    medida: "35X35 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "35X35 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "120",
    nome: "Tecnopano Gr Diversas Cores 3.5 x 7.0 Zig-Zag",
    descricao: "Tecnopano Gr Diversas Cores 3.5 x 7.0 Zig-Zag",
    acabamento: "Zig-Zag",
    cor: "Diversas Cores",
    medida: "35x70 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "35x70 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "101",
    nome: "Gr2 lavado",
    descricao: "Gr2 lavado",
    acabamento: "Lavado",
    cor: "Variados",
    medida: "3.4",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "3.4",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "180",
    nome: "GR KG 4.4",
    descricao: "GR KG 4.4",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "8",
    nome: "Avental tecnopano Frz unidade cod 000008",
    descricao: "Avental tecnopano Frz unidade cod 000008",
    acabamento: "Overlock",
    cor: "Branco",
    medida: "P,M,G,GG",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "P,M,G,GG",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "224",
    nome: "BR overlocado por kilo",
    descricao: "BR overlocado por kilo",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "30x30 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "30x30 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "224",
    nome: "BR overlocado por kilo",
    descricao: "BR overlocado por kilo",
    acabamento: "Overlock",
    cor: "Variado",
    medida: "40x40 Cm",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "40x40 Cm",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  },
    {
    codigo: "205",
    nome: "Campo cirúrgico tecnopano",
    descricao: "Campo cirúrgico tecnopano",
    acabamento: null,
    cor: "Variado",
    medida: "Variado",
    foto: null,
    notaFiscal: null,
    unidadeMedida: "Variado",
    precoCusto: "0.00",
    precoVenda: "0.00",
    ativo: true
  }
];
